on: [push, pull_request]
name: xcompile
env:
  PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get install cmake pkg-config libfreetype6-dev fontconfig libfontconfig libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            README.md
            LICENSE
